### ISSUE TITLE
Error with bitmap.

### ISSUE THREAD

**Issue by MandiYang** [Len-Stevens/Python-Antivirus#6]
## Using Ubuntu 22.04 Wayland Gnome with python3.10 and can't browse files to scan.

I am trying so solve it with  https://stackoverflow.com/questions/20860325/python-3-tkinter-iconbitmap-error-in-ubuntu and https://stackoverflow.com/questions/70742619/tkinter-tclerror-bitmap-icon-ico-not-defined right now. I think that the problem is that only windows can read `.ico` files.

```
Traceback (most recent call last):
  File "/home/mandi/TEMP/Python-Antivirus/Antivirus.py", line 767, in <lambda>
    self.SelectFileButton.clicked.connect(lambda: browseFiles(MainWindow, self))
  File "/home/mandi/TEMP/Python-Antivirus/Antivirus.py", line 365, in browseFiles
    root.iconbitmap(current_dir + '\\res\\ico\\AntiVirus_ico.ico')
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/mandi/TEMP/Python-Antivirus\res\ico\AntiVirus_ico.ico" not defined
```

**Comment by cookie0o** [comment]
Error fixed. Hope its working for you!

**Comment by MandiYang** [comment]
#12
